"""

Django settings for config project.



Generated by 'django-admin startproject' using Django 4.2.



For more information on this file, see

https://docs.djangoproject.com/en/4.2/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/4.2/ref/settings/

"""



from pathlib import Path

import os

import django.middleware.locale
from django.utils.translation import gettext_lazy as _



# Build paths inside the project like this: BASE_DIR / 'subdir'.



# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-^6ta(ziiz__q95-&9a3x^@-c&_y65+3%#()*klu^rb22&hw2c^'



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True



if DEBUG == True:

    from .development import *

else:

    from .production import *



ALLOWED_HOSTS = ["*"]



# Application definition



INSTALLED_APPS = [

    'modeltranslation',



    'jazzmin',

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'ckeditor',

    'ckeditor_uploader',



    # docs

    'drf_yasg',



    # rest

    'rest_framework',



    # apps

    'apps.main_page',

    'apps.data',

]



MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]



ROOT_URLCONF = 'config.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'config.wsgi.application'



REST_FRAMEWORK = {

    'DEFAULT_PERMISSION_CLASSES': [

        'rest_framework.permissions.AllowAny',

    ],

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',

    'PAGE_SIZE': 8,



    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

}



# Database

# https://docs.djangoproject.com/en/4.2/ref/settings/#databases



DATABASES = DATABASES



# Password validation

# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]



# Ckeditor

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'  # URL to jQuery

CKEDITOR_IMAGE_BACKEND = "pillow"  # Путь к пакету Pillow для обработки изображений

CKEDITOR_CONFIGS = {

    'default': {

        'toolbar': 'Custom',  # Вы можете настроить свою собственную панель инструментов CKEditor

        'height': 300,

        'width': 800,

    },

}



# Internationalization

# https://docs.djangoproject.com/en/4.2/topics/i18n/



LANGUAGES = (

    ('ky', _('Kyrgyz')),

    ('ru', _('Russian')),

    ('en', _('English')),

) 






LANGUAGE_CODE = 'ru'



TIME_ZONE = 'UTC'



USE_I18N = True


LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]



USE_TZ = True



# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/4.2/howto/static-files/



STATIC_URL = "/back-static/"

STATIC_ROOT = os.path.join(BASE_DIR, "back-static")



MEDIA_URL = '/back-media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "back-media")





CKEDITOR_UPLOAD_PATH = "uploads/"



# Default primary key field type

# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





SPECTACULAR_SETTINGS = {

    'TITLE': 'NCOMID API',

    'DESCRIPTION': 'NCOMID description',

    'VERSION': '1.0.0',

    'SERVE_INCLUDE_SCHEMA': False,

}



# CSRF_TRUSTED_ORIGINS = ['*']



CORS_ALLOW_ALL_ORIGINS = True



CORS_ALLOW_CREDENTIALS = True



CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']

CORS_ALLOW_HEADERS = ['Authorization', 'Content-Type', "Accept-Language"]



DATA_UPLOAD_MAX_MEMORY_SIZE = 20000000